ALTER TABLE clean_confirmation
MODIFY COLUMN user_id VARCHAR(20),
MODIFY COLUMN page VARCHAR(50);

ALTER TABLE clean_home
MODIFY COLUMN user_id VARCHAR(20),
MODIFY COLUMN page VARCHAR(50);

ALTER TABLE clean_payment
MODIFY COLUMN user_id VARCHAR(20),
MODIFY COLUMN page VARCHAR(50);

ALTER TABLE clean_search
MODIFY COLUMN user_id VARCHAR(20),
MODIFY COLUMN page VARCHAR(50);

ALTER TABLE clean_users
MODIFY COLUMN user_id VARCHAR(20),
MODIFY COLUMN date DATE,
MODIFY COLUMN device VARCHAR(10),
MODIFY COLUMN sex VARCHAR(10);
